### ISSUE TITLE
Waypoint highlighting stopped working for widgets added with `the_widget`

### ISSUE THREAD

**Issue by christophherr** [shazahm1/Easy-Table-of-Contents#46]
Hi,
Thank you for your work on this plugin. 
I am not sure if my problem is too much of an edge case.

After #26 was merged, the waypoint highlighting for my widget added in a template with `the_widget( 'ezTOC_Widget' );` stopped working (i.e. does not pass the `is_eligible()` check).

Adding the following to `is_eligible()` restores the highlighting:
```[php]
global $wp_widget_factory;

if ( $enabled && $wp_widget_factory->widgets['ezTOC_Widget'] ) {
    return true;
};
```
Is there a better way or could this check be added to the plugin?

**Comment by shazahm1** [comment]
@christophherr 

That seems odd because I'm pretty certain the widget does not include the `is_eligible()` check at all.

To help me better understand...

 - The widget still displays, correct?
 - Do the TOC links still work? Meaning does the page scroll to the correct section?
 - Which version of ezTOC do you have installed?

If it is not the release candidate for version 2.0, please install it to see if the issue persists. Here is the download link:

https://github.com/shazahm1/Easy-Table-of-Contents/archive/2.0-rc1.zip

Version 2.0 has been substantially refactored so I'd rather not try to debug an old version.

**Comment by christophherr** [comment]
@shazahm1 

Thank you for your quick response. 

The widget still displays.
The TOC links don't work. (I had not tested that before)
I tried versions 1.7 and 2.0-rc1

In 2.0-rc1, the processing stops here: https://github.com/shazahm1/Easy-Table-of-Contents/blob/master/easy-table-of-contents.php#L540
If I "pass" this conditional, everything works again.

**Comment by shazahm1** [comment]
@christophherr 

Not sure why that conditional would affect your use case. That condition is only ever run in context of `the_content` filter. 

Could you give the minimal code necessary to duplicate this?

**Comment by christophherr** [comment]
I am using a single category template and outputting the widget with

```[php]
echo '<aside class="sidebar">';
	the_widget( 'ezTOC_Widget' );
echo '</aside>';
```

**Comment by shazahm1** [comment]
@christophherr 

Ok, I'll try to duplicate. I probably will not get to this for a week or so.

Actually, it just occurred to me, I know the exact issue... I was focused on the wrong code path. The widget is working fine. The post content is not being processed, adding the required headings ID/s because it does not pass the widget check as you correctly identified.

Adding the check you suggested initially probably would not work because it would always be true when the plugin is activated.

I can not think of a solution off the top of my head, but I'll give it some thought. I am open to suggestions.

Perhaps adding a filter you can hook into to override the `is_eligible()` check???

**Comment by christophherr** [comment]
@shazahm1 
A filter should be fine but I understand if this is too much of an edge case. 
Thank you again :)
