### ISSUE TITLE
Possible to extract the TOC from the_content()?

### ISSUE THREAD

**Issue by josephkmh** [shazahm1/Easy-Table-of-Contents#84]
Hi there, I'm wondering if there is a way to extract the TOC from the_content(). I am comfortable with PHP, so I'm happy to use any hooks/filters that are exposed, but I'm having a hard time finding them.

As far as I can tell, the TOC is generated and prepended/appended to `the_content()` in one step within `ezTOC::the_content()` - is that correct? Is there any way to extract _just_ the TOC block itself, so I can put it in a different place (not directly before or after `the_content()`)?

**Comment by digiiitalmb** [comment]
Wondering same thing.

**Comment by shazahm1** [comment]
I think this could work:

``` php
$post = ezTOC_Post::get( x );
$toc = $post->getTOC();
```

`x` equals the Post ID

**Comment by digiiitalmb** [comment]
> I think this could work:
> 
> ```
> $post = ezTOC_Post::get( x );
> $toc = $post->getTOC();
> ```
> 
> `x` equals the Post ID

Basically problem is that when shortcode is used but autoinsert is disabled scripts not being loaded, because is_eligible() function returns false in such case. 

I assume there is no way to check if shortcode was used outside of the_content() hence there is no such check. I have buchered code to make it work for my purposes by doing this:

added second parameter to build() function $headings_only = false;
then in is_eligible() function I added `return TRUE;` below is_front_page() check.
 

`public static function build( $post,$headings_only = false) {

			$css_classes = '';

			$html    = '';
			$find    = array();
			$replace = array();
			$items   = self::extract_headings( $find, $replace, $post );

			if($headings_only){

				wp_enqueue_script( 'ez-toc-js' );
				return array( 'find' => $find, 'replace' => $replace, 'content' => $html );

			}
                         /* resto of function code */

`

then in `the_content` function changed `$args    = self::build( $post,true );` to set $headings_only parameter to true.

It works for my purposes, but I know it may break some other functionality potentially.

**Comment by shazahm1** [comment]
@digiiitalmb 

ok, the code you've altered is old and does not exists anymore. the snippet I suggested is based on the new code so would not work.

**Comment by shazahm1** [comment]
Oh, I forgot about this, you can use:

``` php
get_ez_toc_block( $post );
```

where `$post` is either an instance of WP_Post or the post ID.

**Comment by Szymon-dziewonski** [comment]
@shazahm1 thanks for reply, I have question, how Can I make it work? I've got "Undefined function 'get_ez_toc_block'."
Is there hook before/after appending ToC? Or at best some callback to alter existing toc html.
Because right now using filter `the_content` it is not possible, can you please help out?
